name: Frontend Production Deploy

on:
  repository_dispatch:
    types: [fe-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO: ${{ github.event.client_payload.repo }}
      BRANCH: ${{ github.event.client_payload.branch }}
      COMMIT: ${{ github.event.client_payload.commit }}
      AUTHOR: ${{ github.event.client_payload.author }}
      PUSHED_AT: ${{ github.event.client_payload.pushed_at }}

    steps:
      - name: Checkout Infra Repository
        uses: actions/checkout@v4
      ##############################################################
      # Prepare Common Environment Variables
      ##############################################################
      - name: Prepare Slack ENV
        run: |
          echo "SERVICE_NAME=Frontend Prod" >> $GITHUB_ENV
          echo "SHORT_COMMIT=${COMMIT:0:7}" >> $GITHUB_ENV
          echo "RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          echo "BUILD_START_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "TS=$(date +%s)" >> $GITHUB_ENV

      ##############################################################
      # Start Slack Message
      ##############################################################
      - name: Send Slack Start Message
        run: |
          envsubst < "${GITHUB_WORKSPACE}/.slack/start.json" > slack-start.json

          curl -s -X POST \
            -H "Content-type: application/json" \
            --data @slack-start.json \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      ##############################################################
      # Deploy to Production FE Server
      ##############################################################
      - name: Deploy to FE Production Server
        id: deploy-step
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.ONPREM_HOST }}
          username: ${{ secrets.ONPREM_USER }}
          password: ${{ secrets.ONPREM_SSH_PASSWORD }}
          port: ${{ secrets.ONPREM_SSH_PORT }}
          script: |
            cd ${{ secrets.FRONTEND_PROD_WORKING_DIR }}

            git fetch origin
            git reset --hard origin/${BRANCH}

            docker compose down
            docker compose up -d --build

            docker image prune -f

      ##############################################################
      # Success Slack Message
      ##############################################################
      - name: Send Slack Success Message
        if: success()
        run: |
          echo "TS=$(date +%s)" >> $GITHUB_ENV

          envsubst < "${GITHUB_WORKSPACE}/.slack/success.json" > slack-success.json

          curl -s -X POST \
            -H "Content-type: application/json" \
            --data @slack-success.json \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      ##############################################################
      # Failure Slack Message
      ##############################################################
      - name: Send Slack Failure Message
        if: failure()
        run: |
          echo "TS=$(date +%s)" >> $GITHUB_ENV

          envsubst < "${GITHUB_WORKSPACE}/.slack/failure.json" > slack-failure.json

          curl -s -X POST \
            -H "Content-type: application/json" \
            --data @slack-failure.json \
            ${{ secrets.SLACK_WEBHOOK_URL }}
